FROM node:18-alpine
WORKDIR /app
COPY . .
RUN npm install -g snyk && npm install -g snyk-to-html

ARG SNYK_AUTH_TOKEN
ENV SNYK_AUTH_TOKEN=$SNYK_AUTH_TOKEN

ARG OUTPUT_FILENAME
ENV OUTPUT_FILENAME=$OUTPUT_FILENAME

RUN snyk auth $SNYK_AUTH_TOKEN && snyk test --json | snyk-to-html -o $OUTPUT_FILENAME.html || true
